#!/bin/bash
python3 -m pymavlink.tools.mavgen --lang=C --wire-protocol=2.0 --output=generated/c/ message_definitions/ironclad.xml
mkdir -p generated/python
python3 -m pymavlink.tools.mavgen --lang=Python --wire-protocol=2.0 --output=generated/python/ironcladmavlink.py message_definitions/ironclad.xml
